/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class armus_lib_parser_Parser */

#ifndef _Included_armus_lib_parser_Parser
#define _Included_armus_lib_parser_Parser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     armus_lib_parser_Parser
 * Method:    run
 * Signature: ([Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_armus_lib_parser_Parser_run
  (JNIEnv *, jobject, jobjectArray);

int pasada1(char **,int);
int pasada2(char **,int);
#ifdef __cplusplus
}
#endif
#endif
