/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class armus_lib_scanner_Scanner */

#ifndef _Included_armus_lib_scanner_Scanner
#define _Included_armus_lib_scanner_Scanner
#ifdef __cplusplus
extern "C" {
#endif
#define MAX_FILE 150
#define MAX_NAME_FILE 256*4    
    /*
     * Class:     armus_lib_scanner_Scanner
     * Method:    lsFiles
     * Signature: (Ljava/lang/String;)[Ljava/lang/String;
     */
    JNIEXPORT jobjectArray JNICALL Java_armus_lib_scanner_Scanner_lsFiles
    (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
