/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class armus_lib_scanner_Scanner */

#ifndef _Included_armus_lib_scanner_Scanner
#define _Included_armus_lib_scanner_Scanner
#ifdef __cplusplus
extern "C" {
#endif   
    /*
     * Class:     armus_lib_scanner_Scanner
     * Method:    lsFiles
     * Signature: (Ljava/lang/String;)[Ljava/lang/String;
     */
    JNIEXPORT jobjectArray JNICALL Java_armus_lib_scanner_Scanner_lsFiles
    (JNIEnv *, jobject, jstring);
    
    /*
    * Class:     armus_lib_scanner_Scanner
    * Method:    lsTokens
    * Signature: (Ljava/lang/String;)[Ljava/lang/String;
    */
   JNIEXPORT jobjectArray JNICALL Java_armus_lib_scanner_Scanner_lsTokens
     (JNIEnv *, jobject, jobjectArray);

    
    
    char** obtenerArchivosIncluir(const char *strFirstFile);
    char **unirListaArchivos(char **listaPreliminar,char **masArchivos);
    char *obtenerDirectorio(const char *strFirstFile);
    char *obtenerNombreBase(const char *strFirstFile);
#ifdef __cplusplus
}
#endif
#endif
